# Generated by Django 3.1.6 on 2021-04-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='matriculados',
            field=models.IntegerField(default=0),
        ),
    ]
