# Generated by Django 3.1.6 on 2021-05-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detallematricula',
            unique_together={('alumno', 'curso', 'semestre')},
        ),
    ]
