# Generated by Django 3.1.7 on 2021-04-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0002_curso_matriculados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='fechaNacimiento',
        ),
    ]
