# Generated by Django 3.1.6 on 2021-05-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0002_auto_20210501_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nombreCurso',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
