# Generated by Django 3.1.7 on 2021-04-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0003_auto_20210421_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='matriculados',
            new_name='vacantes',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='email',
        ),
        migrations.AddField(
            model_name='alumno',
            name='activo',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='detallematricula',
            name='semestre',
            field=models.CharField(default='2020-0', max_length=255),
        ),
        migrations.AddField(
            model_name='profesor',
            name='activo',
            field=models.BooleanField(default=0),
        ),
    ]
