# Generated by Django 3.1.6 on 2021-04-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0004_auto_20210421_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='activo',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='activo',
            field=models.BooleanField(default=1),
        ),
    ]
