# Generated by Django 3.1.7 on 2021-04-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0005_auto_20210426_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='matriculados',
            field=models.IntegerField(default=0),
        ),
    ]
