# Generated by Django 3.1.6 on 2021-04-28 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0005_auto_20210426_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSemestre', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='detallematricula',
            name='semestre',
        ),
        migrations.CreateModel(
            name='semestreCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacantes', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='matricula.curso')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestre', to='matricula.semestre')),
            ],
        ),
    ]
