# Generated by Django 3.1.7 on 2021-04-28 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0006_curso_matriculados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='matriculados',
        ),
    ]
